apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: e2e-lane-vue-nest
  namespace: colossus-e2e-lane-vue-nest
  labels:
    app: e2e-lane-vue-nest
    managed-by: colossus
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: ubuntu.desmana-truck.ts.net
      http:
        paths:
          - path: /e2e-lane-vue-nest(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: e2e-lane-vue-nest
                port:
                  number: 80
  tls:
    - hosts:
        - ubuntu.desmana-truck.ts.net
      secretName: colossus-shared-tls
